{% set name = "pydot" %}
{% set version = "4.0.1" %}
{% set sha256 = "c2148f681c4a33e08bf0e26a9e5f8e4099a82e0e2a068098f32ce86577364ad5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true  # [py<38]

requirements:
  host:
    - pip
    - python
    - setuptools >=75.3.2
  run:
    - python
    - pyparsing >=3.1.0
    # Cautious pinning
    - graphviz <3

test:
  imports:
    - pydot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pydot/pydot
  license: MIT
  license_family: MIT
  license_file: LICENSES/MIT.txt
  summary: Python interface to Graphviz's Dot
  description: |
    This module provides with a full interface to create handle modify and
    process graphs in Graphviz’s dot language.
  doc_url: https://pypi.org/pypi/pydot
  dev_url: https://github.com/pydot/pydot

extra:
  recipe-maintainers:
    - nehaljwani
    - leycec
