{% set name = "pydot" %}
{% set version = "1.4.2" %}
{% set sha256 = "248081a39bcb56784deb018977e428605c1c758f10897a339fce1dd728ff007d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: True  # [py<35]

requirements:
  host:
    - pip
    - python
    - pyparsing
    - setuptools
    - wheel
  run:
    - python
    - pyparsing >=2.1.4,<3
    # Cautious pinning
    - graphviz <3

test:
  imports:
    - pydot
  commands:
    - pip check
  requires:
    - pip
  
about:
  home: https://github.com/pydot/pydot
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python interface to Graphviz's Dot
  description: |
      This module provides with a full interface to create handle modify and
      process graphs in Graphviz’s dot language.
  doc_url: https://pypi.python.org/pypi/pydot
  dev_url: https://github.com/pydot/pydot

extra:
  recipe-maintainers:
    - nehaljwani
    - leycec
