{% set name = "pydot" %}
{% set version = "4.0.1" %}
{% set sha256 = "c2148f681c4a33e08bf0e26a9e5f8e4099a82e0e2a068098f32ce86577364ad5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true  # [py<38]

requirements:
  host:
    - pip
    - python
    - setuptools >=75.3.2
  run:
    - python
    - pyparsing >=3.1.0
    - graphviz

# Graphviz regression tests that fail on Windows due to platform differences
# in graphviz image rendering output (image checksum mismatches in
# `_compare_images`).
{% set deselect_tests = " --deselect=test/test_pydot.py::TestGraphvizRegressions::test_regression_002_alf" %}
{% set deselect_tests = deselect_tests + " --deselect=test/test_pydot.py::TestGraphvizRegressions::test_regression_006_b102" %}
{% set deselect_tests = deselect_tests + " --deselect=test/test_pydot.py::TestGraphvizRegressions::test_regression_007_b106" %}
{% set deselect_tests = deselect_tests + " --deselect=test/test_pydot.py::TestGraphvizRegressions::test_regression_012_b143" %}
{% set deselect_tests = deselect_tests + " --deselect=test/test_pydot.py::TestGraphvizRegressions::test_regression_018_b29" %}
{% set deselect_tests = deselect_tests + " --deselect=test/test_pydot.py::TestGraphvizRegressions::test_regression_026_b53" %}
{% set deselect_tests = deselect_tests + " --deselect=test/test_pydot.py::TestGraphvizRegressions::test_regression_028_b56" %}
{% set deselect_tests = deselect_tests + " --deselect=test/test_pydot.py::TestGraphvizRegressions::test_regression_069_decorate" %}
{% set deselect_tests = deselect_tests + " --deselect=test/test_pydot.py::TestGraphvizRegressions::test_regression_134_Latin1" %}
{% set deselect_tests = deselect_tests + " --deselect=test/test_pydot.py::TestGraphvizRegressions::test_regression_140_lsunix" %}
{% set deselect_tests = deselect_tests + " --deselect=test/test_pydot.py::TestGraphvizRegressions::test_regression_141_mike" %}
{% set deselect_tests = deselect_tests + " --deselect=test/test_pydot.py::TestGraphvizRegressions::test_regression_144_NaN" %}
{% set deselect_tests = deselect_tests + " --deselect=test/test_pydot.py::TestGraphvizRegressions::test_regression_173_states" %}
{% set deselect_tests = deselect_tests + " --deselect=test/test_pydot.py::TestGraphvizRegressions::test_regression_176_trapeziumlr" %}
{% set deselect_tests = deselect_tests + " --deselect=test/test_pydot.py::TestGraphvizRegressions::test_regression_180_unix" %}
{% set deselect_tests = deselect_tests + " --deselect=test/test_pydot.py::TestGraphvizRegressions::test_regression_181_unix2k" %}

test:
  source_files:
    - test
    - setup.cfg
  imports:
    - pydot
    - pydot.core
    - pydot.classes
    - pydot.exceptions
    - pydot.dot_parser
  commands:
    - pip check
    - pytest -ra -v -n auto test  # [not win]
    - pytest -ra -v -n auto test {{ deselect_tests }}  # [win]
  requires:
    - pip
    - pytest
    - chardet
    - parameterized
    - pytest-xdist

about:
  home: https://github.com/pydot/pydot
  license: MIT
  license_family: MIT
  license_file:
    - LICENSES/MIT.txt
    - LICENSES/Python-2.0.txt
  summary: Python interface to Graphviz's Dot
  description: |
    This module provides with a full interface to create handle modify and
    process graphs in Graphviz’s dot language.
  doc_url: https://pypi.org/pypi/pydot
  dev_url: https://github.com/pydot/pydot

extra:
  recipe-maintainers:
    - nehaljwani
    - leycec
