{% set name = "pydot" %}
{% set version = "3.0.4" %}
{% set sha256 = "3ce88b2558f3808b0376f22bfa6c263909e1c3981e2a7b629b65b451eee4a25d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: True  # [py<38]

requirements:
  host:
    - pip
    - python
    - pyparsing
    - setuptools >=61.0
    - wheel
  run:
    - python
    - pyparsing >=3.0.9
    # Cautious pinning
    - graphviz <3

test:
  imports:
    - pydot
  commands:
    - pip check
  requires:
    - pip
  
about:
  home: https://github.com/pydot/pydot
  license: MIT
  license_family: MIT
  license_file: LICENSES/MIT.txt
  summary: Python interface to Graphviz's Dot
  description: |
      This module provides with a full interface to create handle modify and
      process graphs in Graphviz’s dot language.
  doc_url: https://pypi.python.org/pypi/pydot
  dev_url: https://github.com/pydot/pydot

extra:
  recipe-maintainers:
    - nehaljwani
    - leycec
