travis:
  secure:
    BINSTAR_TOKEN: bMYNXyaR/AXMXT3rKULF6FtVyFR6BUvyYIX9HOWtOBUU417Oj0g6n+WybzU2Uuwa+QMgsbebhumxs5OKA+y/fZrTnS+3CHZatjCgKIlC4xkBYZUW0MvgiVhaSXhMuq6z3zBVbhzB2m0WcEWs/cO3wpeNkUCkmZQl1NhialKesgwiSTqUSclomjI7NZC1TeuC8mTXlwIG1HbdOhdUT1n4OL0//FXah66LWKfLDwK5dkt3t4Pro7xLgIIrk9Hd75tWpsGhDToj36RE3jll7tUVf+SL3hbsPgaqthldhqv4I2oDCGWAw1gYwHCec1do7nZDWQC0p32la3WGeQINE1FhQBLTiwYJB8Ra76ibkjHA92IayJyciFIOmapklO2vl6lEKpNj7YdjAtLEo9GjNsGsGiyXGd4lf1JhaPmaAdkb2Xw8X15dyjSOUefB2YfConaVKfebRCv6yM3Fg1LoX7uO3D9cMwQnNBOR70UPhxy9inmdpCk3U9jd9uf4PmCHP9IEQcenYJZahnzlE+6d3TuiGDGpXYYXMCo7PdeD7Ymvu+oUX33IJty6Gxd16sm/4Af/NibLMMAa7tWmjme+Fu2B05Xge1I5VmPE8PXQyxQ5TO41r1WrCotAvsGKZRp5u5AsltjWXkrSsyuK4yhLCxJKGSRpg8ElmbygyOThb+X6bMc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
