travis:
  secure:
    BINSTAR_TOKEN: F4S9t7hDw1svGA/gLWJlzo5uWX/SXK0blODFQBqjJZewDGCscu1IdhBZNY61FiUfe+/j/er6M+Xd1E5a1N/K2TmvobwxUZVXaknv0PQ7uvRtF/LPa+oPoIJTRsT6eRCWcuyCpZb5RA8TjeIR0Q0r1Zty1ZXrtWBNn+sM3PTzp0rrDApni6UitVOVfGSHFzkh9nXSoUr9AegxeE4nHYPwPGToC4pG2NR2sriZ5HpGCo/3R0t4KzjeYk/fiYLFKfgUUubnrKZX0t+Jv2U1aTO7dP8K+oys6Ut8vQktojfIz55zMuIFWikcoeHx/h+GCiAH6kc52OHJ5Zt2uwoA/qX0lFEWrwrhPL0AClVvor4owwrbdAbE72mGZXfXSyseSXiV4DvaK5nXmirDN2aRVmAvgwV4HIJAFlawI2pbEhePq25guee4mADlG8/+NoPFEW5SOS/y8W0iOqnmi3/zTtEkyK2LdrYk0Oc9monzt1K/H5BGMgjCAPDB3KfPziscBYR0SRjSx2O4pCs0fubby4fr7NtS2pLNpRXEHq6U+nNvkVZkq+CanCd6Hcj+cZnIENBzapN4OQMZ9q2TJPIPTd7GD4BYHdMV1zWxUDEVybZ2pjNebEDCQkKjQPxegULWR2oFTtzBKc0w3lzRT5nxNwC15xi6eqEme1AJR1AvEVuxxZ0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
