travis:
  secure:
    BINSTAR_TOKEN: aBl5Y3Jrry5lVjvXZ2eWkAKgGfZHdtbgvNEqLEAEIx3jV1nec0A7p4S5veuHXVI2pJ+rTW2sogXUe/xTGpNBdw+uCjCM3hliJdR9x0+kDu6ghcXEGDlNpaZTiNBzhNJL1+523eqVDatGa3QQqqlBP6USEISInK6EMKl4kSIMQ8Xra60WGLQJCIOEaTz7JmqsOV+tjC8Un2tQokXTr/wvXAbTAk/PMSVMrsz2zjYCoCH5EHvB+xpZavIvakGTf3w56jc2NEUL42QxmfdTdFw0B7WwLVaKb1ClJV+qXQ/UaFJJNbhqLtRz9lup9r/3V4Zu6QoLh3Ode7JYce33FP8Rdgf5WZ6Db4XlaXit66xaVM9kczj+yxRhHEIXJHBwux352JFBuj3jk9WDU/cR6lDFfJwszr3UcH029yrQYtDyZ1u1r7E7NZoH1HPYtaTQd4yPF8NjK0mq1NoK5ZYD4EmHYzSr+kunzhaJeA2WSLHI+s7kgXwvxL5UgdO9VKjg0wFAx4Lsz4S7XQbUU56kOvkroXw6OPM2zhfesI8aOxtbLzyMkMtcy11MX5RxcsN3DDZjWZG2tUnJhBnrYeg7YpKegR09Ho4hashTquQkuJaM0WwhMjHmArvWv9xe5J4odFNCZqPmmO2xjA5GOsAoeZ2hBMmSMLuVYCOMS4dU3T5DTm0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
